import './globals.css';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>
        
        <header className='bg-gray-200'>
          <div>
            <Link href="/"> 
              <Image
              src='/Logo.png'
              height={0}
              width={200}
              alt={`Image de logo`}
            />
             </Link>



<nav className="flex justify-end pb-4 ">
        <Link href="/Login">
          <button
            type="button"
            className="bg-blue-500 hover:bg-blue-600 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-6 py-3 mb-2 dark:bg-blue-700 dark:hover:bg-blue-800 focus:outline-none dark:focus:ring-blue-800 ml-2"
          >
            <span className="inline-block text-white">Login</span>
          </button>
        </Link>
        <Link href="/Inscription">
          <button
            type="button"
            className="bg-blue-500 hover:bg-blue-600 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-6 py-3 mb-2 dark:bg-blue-700 dark:hover:bg-blue-800 focus:outline-none dark:focus:ring-blue-800 ml-2"
          >
            <span className="inline-block text-white">Inscription </span>
          </button>
        </Link>
        <Link href="/PageAdmin">
          <button
            type="button"
            className=" w-[150px] bg-blue-500 hover:bg-blue-600 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-6 py-3 mb-2 dark:bg-blue-700 dark:hover:bg-blue-800 focus:outline-none dark:focus:ring-blue-800 ml-2"
          >
            <span className="inline-block text-white">Page Admin </span>
          </button>
        </Link>

        <Link href="/Panier">
          <button
            type="button"
            className=" w-[150px] bg-blue-500 hover:bg-blue-600 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-6 py-3 mb-2 dark:bg-blue-700 dark:hover:bg-blue-800 focus:outline-none dark:focus:ring-blue-800 ml-2"
          >
            <span className="inline-block text-white">Panier  </span>
          </button>
        </Link>
      </nav>


            </div>
        </header>
        {/* Contenu principal */}
        {children}
        <footer className="my-8">
          <p className="text-center">
            &copy; 2023 Supports Ordinateur et tablette. Tous droits réservés.
          </p>
        </footer>
      </body>
    </html>
  );
}



