import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Ajouter ici votre balise d'en-tête */}
      </head>
      <body className={inter.className}>
        {/* Ajouter ici votre balise d'en-tête */}
        <header>
          {/* Contenu de votre en-tête */}
        </header>
        {/* Contenu principal */}
        {children}
        <footer className="my-8">
          <p className="text-center">
            &copy; 2023 Supports Ordinateur et tablette. Tous droits réservés.
          </p>
        </footer>
      </body>
    </html>
  );
}



